/* tslint:disable */
/* eslint-disable */
/**
 * Private Proof Delegation-CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  IssueCoSnarkCodeRequest,
  ScheduleJobRequest,
  ScheduleJobResponse,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    IssueCoSnarkCodeRequestFromJSON,
    IssueCoSnarkCodeRequestToJSON,
    ScheduleJobRequestFromJSON,
    ScheduleJobRequestToJSON,
    ScheduleJobResponseFromJSON,
    ScheduleJobResponseToJSON,
} from '../models/index';

export interface AddInputRequest {
    id: string;
    inputParty0: Blob;
    inputParty1: Blob;
    inputParty2: Blob;
}

export interface IssueCosnarkCodeRequest {
    issueCoSnarkCodeRequest: IssueCoSnarkCodeRequest;
}

export interface ScheduleJobOperationRequest {
    scheduleJobRequest: ScheduleJobRequest;
}

/**
 * 
 */
export class JobApi extends runtime.BaseAPI {

    /**
     * add input data to a job
     */
    async addInputRaw(requestParameters: AddInputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addInput().'
            );
        }

        if (requestParameters['inputParty0'] == null) {
            throw new runtime.RequiredError(
                'inputParty0',
                'Required parameter "inputParty0" was null or undefined when calling addInput().'
            );
        }

        if (requestParameters['inputParty1'] == null) {
            throw new runtime.RequiredError(
                'inputParty1',
                'Required parameter "inputParty1" was null or undefined when calling addInput().'
            );
        }

        if (requestParameters['inputParty2'] == null) {
            throw new runtime.RequiredError(
                'inputParty2',
                'Required parameter "inputParty2" was null or undefined when calling addInput().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['inputParty0'] != null) {
            formParams.append('input_party0', requestParameters['inputParty0'] as any);
        }

        if (requestParameters['inputParty1'] != null) {
            formParams.append('input_party1', requestParameters['inputParty1'] as any);
        }

        if (requestParameters['inputParty2'] != null) {
            formParams.append('input_party2', requestParameters['inputParty2'] as any);
        }

        const response = await this.request({
            path: `/api/v1/jobs/{id}/input`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * add input data to a job
     */
    async addInput(requestParameters: AddInputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addInputRaw(requestParameters, initOverrides);
    }

    /**
     * create a new job
     */
    async issueCosnarkCodeRaw(requestParameters: IssueCosnarkCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['issueCoSnarkCodeRequest'] == null) {
            throw new runtime.RequiredError(
                'issueCoSnarkCodeRequest',
                'Required parameter "issueCoSnarkCodeRequest" was null or undefined when calling issueCosnarkCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/jobs/code`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: IssueCoSnarkCodeRequestToJSON(requestParameters['issueCoSnarkCodeRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * create a new job
     */
    async issueCosnarkCode(requestParameters: IssueCosnarkCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.issueCosnarkCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * create a new job
     */
    async scheduleJobRaw(requestParameters: ScheduleJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleJobResponse>> {
        if (requestParameters['scheduleJobRequest'] == null) {
            throw new runtime.RequiredError(
                'scheduleJobRequest',
                'Required parameter "scheduleJobRequest" was null or undefined when calling scheduleJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/jobs/schedule`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleJobRequestToJSON(requestParameters['scheduleJobRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleJobResponseFromJSON(jsonValue));
    }

    /**
     * create a new job
     */
    async scheduleJob(requestParameters: ScheduleJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleJobResponse> {
        const response = await this.scheduleJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
