/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  BlueprintAccess,
  PaginationResultInviteCode,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    BlueprintAccessFromJSON,
    BlueprintAccessToJSON,
    PaginationResultInviteCodeFromJSON,
    PaginationResultInviteCodeToJSON,
} from '../models/index';

export interface CreateNodeInviteCodeRequest {
    distributionMethod?: string | null;
}

export interface CreateNodeInviteCodeBatchRequest {
    batchSize: number;
    distributionMethod?: string | null;
}

export interface CreateUserRequest {
    email: string;
    password: string;
}

export interface CreateUserInviteCodeRequest {
    distributionMethod?: string | null;
}

export interface CreateUserInviteCodeBatchRequest {
    batchSize: number;
    distributionMethod?: string | null;
}

export interface PaginateOpenNodeInvitationsRequest {
    cursor?: number | null;
    perPage?: number | null;
    filter?: string | null;
}

export interface PaginateOpenUserInvitationsRequest {
    cursor?: number | null;
    perPage?: number | null;
    filter?: string | null;
}

export interface RevokeNodeInvitationCodeRequest {
    code: string;
}

export interface RevokeUserInvitationCodeRequest {
    code: string;
}

export interface UpdateBlueprintAccessRequest {
    access: BlueprintAccess;
    id: string;
}

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI {

    /**
     */
    async createNodeInviteCodeRaw(requestParameters: CreateNodeInviteCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['distributionMethod'] != null) {
            formParams.append('distribution_method', requestParameters['distributionMethod'] as any);
        }

        const response = await this.request({
            path: `/admin/node/invitation/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async createNodeInviteCode(requestParameters: CreateNodeInviteCodeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.createNodeInviteCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createNodeInviteCodeBatchRaw(requestParameters: CreateNodeInviteCodeBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['batchSize'] == null) {
            throw new runtime.RequiredError(
                'batchSize',
                'Required parameter "batchSize" was null or undefined when calling createNodeInviteCodeBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['batchSize'] != null) {
            formParams.append('batch_size', requestParameters['batchSize'] as any);
        }

        if (requestParameters['distributionMethod'] != null) {
            formParams.append('distribution_method', requestParameters['distributionMethod'] as any);
        }

        const response = await this.request({
            path: `/admin/node/invitation/batch_create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createNodeInviteCodeBatch(requestParameters: CreateNodeInviteCodeBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createNodeInviteCodeBatchRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createUserRaw(requestParameters: CreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling createUser().'
            );
        }

        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling createUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['email'] != null) {
            formParams.append('email', requestParameters['email'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        const response = await this.request({
            path: `/admin/user/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createUser(requestParameters: CreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createUserRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createUserInviteCodeRaw(requestParameters: CreateUserInviteCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['distributionMethod'] != null) {
            formParams.append('distribution_method', requestParameters['distributionMethod'] as any);
        }

        const response = await this.request({
            path: `/admin/user/invitation/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async createUserInviteCode(requestParameters: CreateUserInviteCodeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.createUserInviteCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createUserInviteCodeBatchRaw(requestParameters: CreateUserInviteCodeBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['batchSize'] == null) {
            throw new runtime.RequiredError(
                'batchSize',
                'Required parameter "batchSize" was null or undefined when calling createUserInviteCodeBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['batchSize'] != null) {
            formParams.append('batch_size', requestParameters['batchSize'] as any);
        }

        if (requestParameters['distributionMethod'] != null) {
            formParams.append('distribution_method', requestParameters['distributionMethod'] as any);
        }

        const response = await this.request({
            path: `/admin/user/invitation/batch_create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createUserInviteCodeBatch(requestParameters: CreateUserInviteCodeBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createUserInviteCodeBatchRaw(requestParameters, initOverrides);
    }

    /**
     */
    async paginateOpenNodeInvitationsRaw(requestParameters: PaginateOpenNodeInvitationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginationResultInviteCode>> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/admin/node/invitation/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginationResultInviteCodeFromJSON(jsonValue));
    }

    /**
     */
    async paginateOpenNodeInvitations(requestParameters: PaginateOpenNodeInvitationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginationResultInviteCode> {
        const response = await this.paginateOpenNodeInvitationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async paginateOpenUserInvitationsRaw(requestParameters: PaginateOpenUserInvitationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginationResultInviteCode>> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/admin/user/invitation/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginationResultInviteCodeFromJSON(jsonValue));
    }

    /**
     */
    async paginateOpenUserInvitations(requestParameters: PaginateOpenUserInvitationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginationResultInviteCode> {
        const response = await this.paginateOpenUserInvitationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async revokeNodeInvitationCodeRaw(requestParameters: RevokeNodeInvitationCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling revokeNodeInvitationCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['code'] != null) {
            formParams.append('code', requestParameters['code'] as any);
        }

        const response = await this.request({
            path: `/admin/node/invitation/revoke`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async revokeNodeInvitationCode(requestParameters: RevokeNodeInvitationCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeNodeInvitationCodeRaw(requestParameters, initOverrides);
    }

    /**
     */
    async revokeUserInvitationCodeRaw(requestParameters: RevokeUserInvitationCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling revokeUserInvitationCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['code'] != null) {
            formParams.append('code', requestParameters['code'] as any);
        }

        const response = await this.request({
            path: `/admin/user/invitation/revoke`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async revokeUserInvitationCode(requestParameters: RevokeUserInvitationCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeUserInvitationCodeRaw(requestParameters, initOverrides);
    }

    /**
     * update the blueprint access
     */
    async updateBlueprintAccessRaw(requestParameters: UpdateBlueprintAccessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['access'] == null) {
            throw new runtime.RequiredError(
                'access',
                'Required parameter "access" was null or undefined when calling updateBlueprintAccess().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateBlueprintAccess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['access'] != null) {
            formParams.append('access', requestParameters['access'] as any);
        }

        if (requestParameters['id'] != null) {
            formParams.append('id', requestParameters['id'] as any);
        }

        const response = await this.request({
            path: `/admin/blueprint/update/access`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * update the blueprint access
     */
    async updateBlueprintAccess(requestParameters: UpdateBlueprintAccessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateBlueprintAccessRaw(requestParameters, initOverrides);
    }

}
