/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  AuxiliaryType,
  BlueprintCurve,
  BlueprintReadyProbe,
  BlueprintType,
  CreateBlueprintResponse,
  NpsKeyMaterial,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    AuxiliaryTypeFromJSON,
    AuxiliaryTypeToJSON,
    BlueprintCurveFromJSON,
    BlueprintCurveToJSON,
    BlueprintReadyProbeFromJSON,
    BlueprintReadyProbeToJSON,
    BlueprintTypeFromJSON,
    BlueprintTypeToJSON,
    CreateBlueprintResponseFromJSON,
    CreateBlueprintResponseToJSON,
    NpsKeyMaterialFromJSON,
    NpsKeyMaterialToJSON,
} from '../models/index';

export interface BlueprintKeyMaterialRequest {
    id: string;
}

export interface BlueprintReadyRequest {
    id: string;
}

export interface CreateRequest {
    curve: BlueprintCurve;
    name: string;
    nodeProvider0: number;
    nodeProvider1: number;
    nodeProvider2: number;
    typ: BlueprintType;
}

export interface IssueCosnarkCodeRequest {
    amount: number;
    validityInSeconds: number;
}

export interface UploadAuxDataRequest {
    id: string;
    auxType: AuxiliaryType;
    file: Blob;
}

/**
 * 
 */
export class BlueprintApi extends runtime.BaseAPI {

    /**
     * returns the key material of the NPSs associated with the blueprint
     */
    async blueprintKeyMaterialRaw(requestParameters: BlueprintKeyMaterialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<NpsKeyMaterial>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling blueprintKeyMaterial().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/blueprint/{id}/key-material`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NpsKeyMaterialFromJSON));
    }

    /**
     * returns the key material of the NPSs associated with the blueprint
     */
    async blueprintKeyMaterial(requestParameters: BlueprintKeyMaterialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NpsKeyMaterial>> {
        const response = await this.blueprintKeyMaterialRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * checks whether a blueprint is already ready
     */
    async blueprintReadyRaw(requestParameters: BlueprintReadyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlueprintReadyProbe>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling blueprintReady().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/blueprint/{id}/ready`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlueprintReadyProbeFromJSON(jsonValue));
    }

    /**
     * checks whether a blueprint is already ready
     */
    async blueprintReady(requestParameters: BlueprintReadyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlueprintReadyProbe> {
        const response = await this.blueprintReadyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * create a new coSNARK blueprint
     */
    async createRaw(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateBlueprintResponse>> {
        if (requestParameters['curve'] == null) {
            throw new runtime.RequiredError(
                'curve',
                'Required parameter "curve" was null or undefined when calling create().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling create().'
            );
        }

        if (requestParameters['nodeProvider0'] == null) {
            throw new runtime.RequiredError(
                'nodeProvider0',
                'Required parameter "nodeProvider0" was null or undefined when calling create().'
            );
        }

        if (requestParameters['nodeProvider1'] == null) {
            throw new runtime.RequiredError(
                'nodeProvider1',
                'Required parameter "nodeProvider1" was null or undefined when calling create().'
            );
        }

        if (requestParameters['nodeProvider2'] == null) {
            throw new runtime.RequiredError(
                'nodeProvider2',
                'Required parameter "nodeProvider2" was null or undefined when calling create().'
            );
        }

        if (requestParameters['typ'] == null) {
            throw new runtime.RequiredError(
                'typ',
                'Required parameter "typ" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['curve'] != null) {
            formParams.append('curve', requestParameters['curve'] as any);
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['nodeProvider0'] != null) {
            formParams.append('node_provider0', requestParameters['nodeProvider0'] as any);
        }

        if (requestParameters['nodeProvider1'] != null) {
            formParams.append('node_provider1', requestParameters['nodeProvider1'] as any);
        }

        if (requestParameters['nodeProvider2'] != null) {
            formParams.append('node_provider2', requestParameters['nodeProvider2'] as any);
        }

        if (requestParameters['typ'] != null) {
            formParams.append('typ', requestParameters['typ'] as any);
        }

        const response = await this.request({
            path: `/api/v1/blueprint/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateBlueprintResponseFromJSON(jsonValue));
    }

    /**
     * create a new coSNARK blueprint
     */
    async create(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateBlueprintResponse> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * create a new job
     */
    async issueCosnarkCodeRaw(requestParameters: IssueCosnarkCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['amount'] == null) {
            throw new runtime.RequiredError(
                'amount',
                'Required parameter "amount" was null or undefined when calling issueCosnarkCode().'
            );
        }

        if (requestParameters['validityInSeconds'] == null) {
            throw new runtime.RequiredError(
                'validityInSeconds',
                'Required parameter "validityInSeconds" was null or undefined when calling issueCosnarkCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['amount'] != null) {
            formParams.append('amount', requestParameters['amount'] as any);
        }

        if (requestParameters['validityInSeconds'] != null) {
            formParams.append('validity_in_seconds', requestParameters['validityInSeconds'] as any);
        }

        const response = await this.request({
            path: `/api/v1/blueprint/code`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * create a new job
     */
    async issueCosnarkCode(requestParameters: IssueCosnarkCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.issueCosnarkCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * add proving key to blueprint
     */
    async uploadAuxDataRaw(requestParameters: UploadAuxDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling uploadAuxData().'
            );
        }

        if (requestParameters['auxType'] == null) {
            throw new runtime.RequiredError(
                'auxType',
                'Required parameter "auxType" was null or undefined when calling uploadAuxData().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadAuxData().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/api/v1/blueprint/{id}/aux/{aux_type}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"aux_type"}}`, encodeURIComponent(String(requestParameters['auxType']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * add proving key to blueprint
     */
    async uploadAuxData(requestParameters: UploadAuxDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.uploadAuxDataRaw(requestParameters, initOverrides);
    }

}
