/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  MpcProtocol,
  ScheduleJobResponse,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    MpcProtocolFromJSON,
    MpcProtocolToJSON,
    ScheduleJobResponseFromJSON,
    ScheduleJobResponseToJSON,
} from '../models/index';

export interface AddInputsRequest {
    inputs0: Blob;
    inputs1: Blob;
    inputs2: Blob;
    jobId: string;
    node0: number;
    node1: number;
    node2: number;
}

export interface DownloadProofRequest {
    id: string;
}

export interface DownloadPublicInputsRequest {
    id: string;
}

export interface DownloadSignatureRequest {
    id: string;
}

export interface ScheduleFullJobRequest {
    blueprintId: string;
    inputs0: Blob;
    inputs1: Blob;
    inputs2: Blob;
    node0: number;
    node1: number;
    node2: number;
    voucher?: string | null;
}

export interface ScheduleFullMultipleInputsJobRequest {
    blueprintId: string;
    node0: number;
    node1: number;
    node2: number;
    deadline?: Date | null;
    voucher?: string | null;
}

export interface ScheduleProveJobRequest {
    blueprintId: string;
    mpcProtocol: MpcProtocol;
    node0: number;
    node1: number;
    node2: number;
    witness0: Blob;
    witness1: Blob;
    witness2: Blob;
    voucher?: string | null;
}

/**
 * 
 */
export class JobApi extends runtime.BaseAPI {

    /**
     * add inputs to a existing job
     */
    async addInputsRaw(requestParameters: AddInputsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['inputs0'] == null) {
            throw new runtime.RequiredError(
                'inputs0',
                'Required parameter "inputs0" was null or undefined when calling addInputs().'
            );
        }

        if (requestParameters['inputs1'] == null) {
            throw new runtime.RequiredError(
                'inputs1',
                'Required parameter "inputs1" was null or undefined when calling addInputs().'
            );
        }

        if (requestParameters['inputs2'] == null) {
            throw new runtime.RequiredError(
                'inputs2',
                'Required parameter "inputs2" was null or undefined when calling addInputs().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling addInputs().'
            );
        }

        if (requestParameters['node0'] == null) {
            throw new runtime.RequiredError(
                'node0',
                'Required parameter "node0" was null or undefined when calling addInputs().'
            );
        }

        if (requestParameters['node1'] == null) {
            throw new runtime.RequiredError(
                'node1',
                'Required parameter "node1" was null or undefined when calling addInputs().'
            );
        }

        if (requestParameters['node2'] == null) {
            throw new runtime.RequiredError(
                'node2',
                'Required parameter "node2" was null or undefined when calling addInputs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['inputs0'] != null) {
            formParams.append('inputs0', requestParameters['inputs0'] as any);
        }

        if (requestParameters['inputs1'] != null) {
            formParams.append('inputs1', requestParameters['inputs1'] as any);
        }

        if (requestParameters['inputs2'] != null) {
            formParams.append('inputs2', requestParameters['inputs2'] as any);
        }

        if (requestParameters['jobId'] != null) {
            formParams.append('job_id', requestParameters['jobId'] as any);
        }

        if (requestParameters['node0'] != null) {
            formParams.append('node0', requestParameters['node0'] as any);
        }

        if (requestParameters['node1'] != null) {
            formParams.append('node1', requestParameters['node1'] as any);
        }

        if (requestParameters['node2'] != null) {
            formParams.append('node2', requestParameters['node2'] as any);
        }

        const response = await this.request({
            path: `/api/v1/jobs/add-inputs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * add inputs to a existing job
     */
    async addInputs(requestParameters: AddInputsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addInputsRaw(requestParameters, initOverrides);
    }

    /**
     */
    async downloadProofRaw(requestParameters: DownloadProofRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling downloadProof().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/jobs/{id}/proof`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async downloadProof(requestParameters: DownloadProofRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.downloadProofRaw(requestParameters, initOverrides);
    }

    /**
     */
    async downloadPublicInputsRaw(requestParameters: DownloadPublicInputsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling downloadPublicInputs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/jobs/{id}/public_inputs`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async downloadPublicInputs(requestParameters: DownloadPublicInputsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.downloadPublicInputsRaw(requestParameters, initOverrides);
    }

    /**
     */
    async downloadSignatureRaw(requestParameters: DownloadSignatureRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling downloadSignature().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/jobs/{id}/signature`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async downloadSignature(requestParameters: DownloadSignatureRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.downloadSignatureRaw(requestParameters, initOverrides);
    }

    /**
     * create a new full job
     */
    async scheduleFullJobRaw(requestParameters: ScheduleFullJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleJobResponse>> {
        if (requestParameters['blueprintId'] == null) {
            throw new runtime.RequiredError(
                'blueprintId',
                'Required parameter "blueprintId" was null or undefined when calling scheduleFullJob().'
            );
        }

        if (requestParameters['inputs0'] == null) {
            throw new runtime.RequiredError(
                'inputs0',
                'Required parameter "inputs0" was null or undefined when calling scheduleFullJob().'
            );
        }

        if (requestParameters['inputs1'] == null) {
            throw new runtime.RequiredError(
                'inputs1',
                'Required parameter "inputs1" was null or undefined when calling scheduleFullJob().'
            );
        }

        if (requestParameters['inputs2'] == null) {
            throw new runtime.RequiredError(
                'inputs2',
                'Required parameter "inputs2" was null or undefined when calling scheduleFullJob().'
            );
        }

        if (requestParameters['node0'] == null) {
            throw new runtime.RequiredError(
                'node0',
                'Required parameter "node0" was null or undefined when calling scheduleFullJob().'
            );
        }

        if (requestParameters['node1'] == null) {
            throw new runtime.RequiredError(
                'node1',
                'Required parameter "node1" was null or undefined when calling scheduleFullJob().'
            );
        }

        if (requestParameters['node2'] == null) {
            throw new runtime.RequiredError(
                'node2',
                'Required parameter "node2" was null or undefined when calling scheduleFullJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['blueprintId'] != null) {
            formParams.append('blueprint_id', requestParameters['blueprintId'] as any);
        }

        if (requestParameters['inputs0'] != null) {
            formParams.append('inputs0', requestParameters['inputs0'] as any);
        }

        if (requestParameters['inputs1'] != null) {
            formParams.append('inputs1', requestParameters['inputs1'] as any);
        }

        if (requestParameters['inputs2'] != null) {
            formParams.append('inputs2', requestParameters['inputs2'] as any);
        }

        if (requestParameters['node0'] != null) {
            formParams.append('node0', requestParameters['node0'] as any);
        }

        if (requestParameters['node1'] != null) {
            formParams.append('node1', requestParameters['node1'] as any);
        }

        if (requestParameters['node2'] != null) {
            formParams.append('node2', requestParameters['node2'] as any);
        }

        if (requestParameters['voucher'] != null) {
            formParams.append('voucher', requestParameters['voucher'] as any);
        }

        const response = await this.request({
            path: `/api/v1/jobs/schedule-full-job`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleJobResponseFromJSON(jsonValue));
    }

    /**
     * create a new full job
     */
    async scheduleFullJob(requestParameters: ScheduleFullJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleJobResponse> {
        const response = await this.scheduleFullJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * create a new full job with multiple inputs
     */
    async scheduleFullMultipleInputsJobRaw(requestParameters: ScheduleFullMultipleInputsJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleJobResponse>> {
        if (requestParameters['blueprintId'] == null) {
            throw new runtime.RequiredError(
                'blueprintId',
                'Required parameter "blueprintId" was null or undefined when calling scheduleFullMultipleInputsJob().'
            );
        }

        if (requestParameters['node0'] == null) {
            throw new runtime.RequiredError(
                'node0',
                'Required parameter "node0" was null or undefined when calling scheduleFullMultipleInputsJob().'
            );
        }

        if (requestParameters['node1'] == null) {
            throw new runtime.RequiredError(
                'node1',
                'Required parameter "node1" was null or undefined when calling scheduleFullMultipleInputsJob().'
            );
        }

        if (requestParameters['node2'] == null) {
            throw new runtime.RequiredError(
                'node2',
                'Required parameter "node2" was null or undefined when calling scheduleFullMultipleInputsJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['blueprintId'] != null) {
            formParams.append('blueprint_id', requestParameters['blueprintId'] as any);
        }

        if (requestParameters['deadline'] != null) {
            formParams.append('deadline', (requestParameters['deadline'] as any).toISOString());
        }

        if (requestParameters['node0'] != null) {
            formParams.append('node0', requestParameters['node0'] as any);
        }

        if (requestParameters['node1'] != null) {
            formParams.append('node1', requestParameters['node1'] as any);
        }

        if (requestParameters['node2'] != null) {
            formParams.append('node2', requestParameters['node2'] as any);
        }

        if (requestParameters['voucher'] != null) {
            formParams.append('voucher', requestParameters['voucher'] as any);
        }

        const response = await this.request({
            path: `/api/v1/jobs/schedule-full-multiple-inputs-job`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleJobResponseFromJSON(jsonValue));
    }

    /**
     * create a new full job with multiple inputs
     */
    async scheduleFullMultipleInputsJob(requestParameters: ScheduleFullMultipleInputsJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleJobResponse> {
        const response = await this.scheduleFullMultipleInputsJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * create a new prove job
     */
    async scheduleProveJobRaw(requestParameters: ScheduleProveJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleJobResponse>> {
        if (requestParameters['blueprintId'] == null) {
            throw new runtime.RequiredError(
                'blueprintId',
                'Required parameter "blueprintId" was null or undefined when calling scheduleProveJob().'
            );
        }

        if (requestParameters['mpcProtocol'] == null) {
            throw new runtime.RequiredError(
                'mpcProtocol',
                'Required parameter "mpcProtocol" was null or undefined when calling scheduleProveJob().'
            );
        }

        if (requestParameters['node0'] == null) {
            throw new runtime.RequiredError(
                'node0',
                'Required parameter "node0" was null or undefined when calling scheduleProveJob().'
            );
        }

        if (requestParameters['node1'] == null) {
            throw new runtime.RequiredError(
                'node1',
                'Required parameter "node1" was null or undefined when calling scheduleProveJob().'
            );
        }

        if (requestParameters['node2'] == null) {
            throw new runtime.RequiredError(
                'node2',
                'Required parameter "node2" was null or undefined when calling scheduleProveJob().'
            );
        }

        if (requestParameters['witness0'] == null) {
            throw new runtime.RequiredError(
                'witness0',
                'Required parameter "witness0" was null or undefined when calling scheduleProveJob().'
            );
        }

        if (requestParameters['witness1'] == null) {
            throw new runtime.RequiredError(
                'witness1',
                'Required parameter "witness1" was null or undefined when calling scheduleProveJob().'
            );
        }

        if (requestParameters['witness2'] == null) {
            throw new runtime.RequiredError(
                'witness2',
                'Required parameter "witness2" was null or undefined when calling scheduleProveJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['blueprintId'] != null) {
            formParams.append('blueprint_id', requestParameters['blueprintId'] as any);
        }

        if (requestParameters['mpcProtocol'] != null) {
            formParams.append('mpc_protocol', requestParameters['mpcProtocol'] as any);
        }

        if (requestParameters['node0'] != null) {
            formParams.append('node0', requestParameters['node0'] as any);
        }

        if (requestParameters['node1'] != null) {
            formParams.append('node1', requestParameters['node1'] as any);
        }

        if (requestParameters['node2'] != null) {
            formParams.append('node2', requestParameters['node2'] as any);
        }

        if (requestParameters['voucher'] != null) {
            formParams.append('voucher', requestParameters['voucher'] as any);
        }

        if (requestParameters['witness0'] != null) {
            formParams.append('witness0', requestParameters['witness0'] as any);
        }

        if (requestParameters['witness1'] != null) {
            formParams.append('witness1', requestParameters['witness1'] as any);
        }

        if (requestParameters['witness2'] != null) {
            formParams.append('witness2', requestParameters['witness2'] as any);
        }

        const response = await this.request({
            path: `/api/v1/jobs/schedule-prove-job`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleJobResponseFromJSON(jsonValue));
    }

    /**
     * create a new prove job
     */
    async scheduleProveJob(requestParameters: ScheduleProveJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleJobResponse> {
        const response = await this.scheduleProveJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
