/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  NodeProvider,
  NodeProviders,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    NodeProviderFromJSON,
    NodeProviderToJSON,
    NodeProvidersFromJSON,
    NodeProvidersToJSON,
} from '../models/index';

export interface ListRequest {
    cursor?: number | null;
    perPage?: number | null;
}

export interface NodeProviderRequest {
    id: number;
}

/**
 * 
 */
export class NodeApi extends runtime.BaseAPI {

    /**
     * get node providers
     */
    async listRaw(requestParameters: ListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<NodeProvider>>> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/node/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NodeProviderFromJSON));
    }

    /**
     * get node providers
     */
    async list(requestParameters: ListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NodeProvider>> {
        const response = await this.listRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * returns the node for the given id
     */
    async nodeProviderRaw(requestParameters: NodeProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodeProvider>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling nodeProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/node/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodeProviderFromJSON(jsonValue));
    }

    /**
     * returns the node for the given id
     */
    async nodeProvider(requestParameters: NodeProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodeProvider> {
        const response = await this.nodeProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * returns 3 randomly chosen node providers
     */
    async randomNodeProvidersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodeProviders>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/node/random-nodes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodeProvidersFromJSON(jsonValue));
    }

    /**
     * returns 3 randomly chosen node providers
     */
    async randomNodeProviders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodeProviders> {
        const response = await this.randomNodeProvidersRaw(initOverrides);
        return await response.value();
    }

}
