/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  PaginationResultNpsHeader,
  RegisterNpsResponse,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    PaginationResultNpsHeaderFromJSON,
    PaginationResultNpsHeaderToJSON,
    RegisterNpsResponseFromJSON,
    RegisterNpsResponseToJSON,
} from '../models/index';

export interface ListRequest {
    cursor?: number | null;
    perPage?: number | null;
}

export interface RegisterRequest {
    cert: string;
    encKey: string;
    grpcUrl: string;
    name: string;
    password: string;
    verifyingKey: string;
    version: string;
}

/**
 * 
 */
export class NPSApi extends runtime.BaseAPI {

    /**
     * get paginated node providers - used for blueprint creators to define clusters
     */
    async listRaw(requestParameters: ListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginationResultNpsHeader>> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/nps/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginationResultNpsHeaderFromJSON(jsonValue));
    }

    /**
     * get paginated node providers - used for blueprint creators to define clusters
     */
    async list(requestParameters: ListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginationResultNpsHeader> {
        const response = await this.listRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * register a new node provider
     */
    async registerRaw(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterNpsResponse>> {
        if (requestParameters['cert'] == null) {
            throw new runtime.RequiredError(
                'cert',
                'Required parameter "cert" was null or undefined when calling register().'
            );
        }

        if (requestParameters['encKey'] == null) {
            throw new runtime.RequiredError(
                'encKey',
                'Required parameter "encKey" was null or undefined when calling register().'
            );
        }

        if (requestParameters['grpcUrl'] == null) {
            throw new runtime.RequiredError(
                'grpcUrl',
                'Required parameter "grpcUrl" was null or undefined when calling register().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling register().'
            );
        }

        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling register().'
            );
        }

        if (requestParameters['verifyingKey'] == null) {
            throw new runtime.RequiredError(
                'verifyingKey',
                'Required parameter "verifyingKey" was null or undefined when calling register().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling register().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['cert'] != null) {
            formParams.append('cert', requestParameters['cert'] as any);
        }

        if (requestParameters['encKey'] != null) {
            formParams.append('enc_key', requestParameters['encKey'] as any);
        }

        if (requestParameters['grpcUrl'] != null) {
            formParams.append('grpc_url', requestParameters['grpcUrl'] as any);
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        if (requestParameters['verifyingKey'] != null) {
            formParams.append('verifying_key', requestParameters['verifyingKey'] as any);
        }

        if (requestParameters['version'] != null) {
            formParams.append('version', requestParameters['version'] as any);
        }

        const response = await this.request({
            path: `/api/v1/nps/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterNpsResponseFromJSON(jsonValue));
    }

    /**
     * register a new node provider
     */
    async register(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterNpsResponse> {
        const response = await this.registerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
