/*
 * TACEO:Proof - CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuxiliaryType {
    #[serde(rename = "pk")]
    Pk,
    #[serde(rename = "vk")]
    Vk,
    #[serde(rename = "circuit")]
    Circuit,
    #[serde(rename = "matrices")]
    Matrices,
}

impl std::fmt::Display for AuxiliaryType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pk => write!(f, "pk"),
            Self::Vk => write!(f, "vk"),
            Self::Circuit => write!(f, "circuit"),
            Self::Matrices => write!(f, "matrices"),
        }
    }
}

impl Default for AuxiliaryType {
    fn default() -> AuxiliaryType {
        Self::Pk
    }
}
