/*
 * TACEO:Proof - CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlueprintReadyProbe {
    #[serde(rename = "missing_aux_data")]
    pub missing_aux_data: Vec<models::AuxiliaryType>,
}

impl BlueprintReadyProbe {
    pub fn new(missing_aux_data: Vec<models::AuxiliaryType>) -> BlueprintReadyProbe {
        BlueprintReadyProbe { missing_aux_data }
    }
}
