/*
 * TACEO:Proof - CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BlueprintAccess {
    #[serde(rename = "Restricted")]
    Restricted,
    #[serde(rename = "Public")]
    Public,
}

impl std::fmt::Display for BlueprintAccess {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Restricted => write!(f, "Restricted"),
            Self::Public => write!(f, "Public"),
        }
    }
}

impl Default for BlueprintAccess {
    fn default() -> BlueprintAccess {
        Self::Restricted
    }
}
