/*
 * TACEO:Proof - CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBlueprintResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
}

impl CreateBlueprintResponse {
    pub fn new(id: uuid::Uuid) -> CreateBlueprintResponse {
        CreateBlueprintResponse { id }
    }
}
