/*
 * TACEO:Proof - CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InviteCode {
    #[serde(
        rename = "distribution_method",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub distribution_method: Option<Option<String>>,
    #[serde(rename = "invite_code")]
    pub invite_code: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl InviteCode {
    pub fn new(invite_code: String, timestamp: String) -> InviteCode {
        InviteCode {
            distribution_method: None,
            invite_code,
            timestamp,
        }
    }
}
