/*
 * TACEO:Proof - CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MpcProtocol {
    #[serde(rename = "Rep3")]
    Rep3,
    #[serde(rename = "Shamir")]
    Shamir,
}

impl std::fmt::Display for MpcProtocol {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Rep3 => write!(f, "Rep3"),
            Self::Shamir => write!(f, "Shamir"),
        }
    }
}

impl Default for MpcProtocol {
    fn default() -> MpcProtocol {
        Self::Rep3
    }
}
