/*
 * TACEO:Proof - CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeProviders {
    #[serde(rename = "node0")]
    pub node0: Box<models::NodeProvider>,
    #[serde(rename = "node1")]
    pub node1: Box<models::NodeProvider>,
    #[serde(rename = "node2")]
    pub node2: Box<models::NodeProvider>,
}

impl NodeProviders {
    pub fn new(
        node0: models::NodeProvider,
        node1: models::NodeProvider,
        node2: models::NodeProvider,
    ) -> NodeProviders {
        NodeProviders {
            node0: Box::new(node0),
            node1: Box::new(node1),
            node2: Box::new(node2),
        }
    }
}
