/*
 * TACEO:Proof - CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleJobResponse {
    #[serde(rename = "job_id")]
    pub job_id: uuid::Uuid,
    #[serde(
        rename = "remaining_permits",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub remaining_permits: Option<Option<i32>>,
}

impl ScheduleJobResponse {
    pub fn new(job_id: uuid::Uuid) -> ScheduleJobResponse {
        ScheduleJobResponse {
            job_id,
            remaining_permits: None,
        }
    }
}
