/*
 * Private Proof Delegation-CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BlueprintCurve {
    #[serde(rename = "Bn254")]
    Bn254,
    #[serde(rename = "Bls381")]
    Bls381,
    #[serde(rename = "Bls377")]
    Bls377,
}

impl std::fmt::Display for BlueprintCurve {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Bn254 => write!(f, "Bn254"),
            Self::Bls381 => write!(f, "Bls381"),
            Self::Bls377 => write!(f, "Bls377"),
        }
    }
}

impl Default for BlueprintCurve {
    fn default() -> BlueprintCurve {
        Self::Bn254
    }
}
