/*
 * Private Proof Delegation-CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BlueprintType {
    #[serde(rename = "CircomGroth16")]
    CircomGroth16,
    #[serde(rename = "LibsnarkGroth16")]
    LibsnarkGroth16,
    #[serde(rename = "NoirUltrahonk")]
    NoirUltrahonk,
}

impl std::fmt::Display for BlueprintType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CircomGroth16 => write!(f, "CircomGroth16"),
            Self::LibsnarkGroth16 => write!(f, "LibsnarkGroth16"),
            Self::NoirUltrahonk => write!(f, "NoirUltrahonk"),
        }
    }
}

impl Default for BlueprintType {
    fn default() -> BlueprintType {
        Self::CircomGroth16
    }
}
