/*
 * Private Proof Delegation-CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBlueprintRequest {
    #[serde(rename = "curve")]
    pub curve: models::BlueprintCurve,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "node_provider0")]
    pub node_provider0: i32,
    #[serde(rename = "node_provider1")]
    pub node_provider1: i32,
    #[serde(rename = "node_provider2")]
    pub node_provider2: i32,
    #[serde(rename = "typ")]
    pub typ: models::BlueprintType,
}

impl CreateBlueprintRequest {
    pub fn new(
        curve: models::BlueprintCurve,
        name: String,
        node_provider0: i32,
        node_provider1: i32,
        node_provider2: i32,
        typ: models::BlueprintType,
    ) -> CreateBlueprintRequest {
        CreateBlueprintRequest {
            curve,
            name,
            node_provider0,
            node_provider1,
            node_provider2,
            typ,
        }
    }
}
