/*
 * Private Proof Delegation-CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueCoSnarkCodeRequest {
    #[serde(rename = "amount")]
    pub amount: i32,
    #[serde(rename = "validity_in_seconds")]
    pub validity_in_seconds: i64,
}

impl IssueCoSnarkCodeRequest {
    pub fn new(amount: i32, validity_in_seconds: i64) -> IssueCoSnarkCodeRequest {
        IssueCoSnarkCodeRequest {
            amount,
            validity_in_seconds,
        }
    }
}
