/*
 * Private Proof Delegation-CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobType {
    #[serde(rename = "Rep3Full")]
    Rep3Full,
    #[serde(rename = "Rep3Prove")]
    Rep3Prove,
    #[serde(rename = "ShamirProve")]
    ShamirProve,
}

impl std::fmt::Display for JobType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Rep3Full => write!(f, "Rep3Full"),
            Self::Rep3Prove => write!(f, "Rep3Prove"),
            Self::ShamirProve => write!(f, "ShamirProve"),
        }
    }
}

impl Default for JobType {
    fn default() -> JobType {
        Self::Rep3Full
    }
}
