/*
 * Private Proof Delegation-CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NpsKeyMaterial {
    #[serde(rename = "enc_key")]
    pub enc_key: String,
    #[serde(rename = "verify_key")]
    pub verify_key: String,
}

impl NpsKeyMaterial {
    pub fn new(enc_key: String, verify_key: String) -> NpsKeyMaterial {
        NpsKeyMaterial {
            enc_key,
            verify_key,
        }
    }
}
