/*
 * Private Proof Delegation-CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterNpsRequest {
    #[serde(rename = "enc_key")]
    pub enc_key: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "verifying_key")]
    pub verifying_key: String,
}

impl RegisterNpsRequest {
    pub fn new(enc_key: String, name: String, verifying_key: String) -> RegisterNpsRequest {
        RegisterNpsRequest {
            enc_key,
            name,
            verifying_key,
        }
    }
}
