/*
 * Private Proof Delegation-CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterNpsResponse {
    #[serde(rename = "nps_id")]
    pub nps_id: i32,
    #[serde(rename = "sns_topic")]
    pub sns_topic: String,
    #[serde(rename = "sqs_queue")]
    pub sqs_queue: String,
}

impl RegisterNpsResponse {
    pub fn new(nps_id: i32, sns_topic: String, sqs_queue: String) -> RegisterNpsResponse {
        RegisterNpsResponse {
            nps_id,
            sns_topic,
            sqs_queue,
        }
    }
}
