/*
 * Private Proof Delegation-CCL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleJobResponse {
    #[serde(rename = "job_id")]
    pub job_id: uuid::Uuid,
    #[serde(rename = "key_material")]
    pub key_material: Vec<models::NpsKeyMaterial>,
    #[serde(rename = "remaining_permits")]
    pub remaining_permits: i32,
}

impl ScheduleJobResponse {
    pub fn new(
        job_id: uuid::Uuid,
        key_material: Vec<models::NpsKeyMaterial>,
        remaining_permits: i32,
    ) -> ScheduleJobResponse {
        ScheduleJobResponse {
            job_id,
            key_material,
            remaining_permits,
        }
    }
}
