/* tslint:disable */
/* eslint-disable */
/**
 * Private Proof Delegation-CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AuxiliaryType = {
    Pk: 'Pk',
    Vk: 'Vk',
    Circuit: 'Circuit'
} as const;
export type AuxiliaryType = typeof AuxiliaryType[keyof typeof AuxiliaryType];


export function instanceOfAuxiliaryType(value: any): boolean {
    for (const key in AuxiliaryType) {
        if (Object.prototype.hasOwnProperty.call(AuxiliaryType, key)) {
            if (AuxiliaryType[key as keyof typeof AuxiliaryType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AuxiliaryTypeFromJSON(json: any): AuxiliaryType {
    return AuxiliaryTypeFromJSONTyped(json, false);
}

export function AuxiliaryTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuxiliaryType {
    return json as AuxiliaryType;
}

export function AuxiliaryTypeToJSON(value?: AuxiliaryType | null): any {
    return value as any;
}

export function AuxiliaryTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AuxiliaryType {
    return value as AuxiliaryType;
}

