/* tslint:disable */
/* eslint-disable */
/**
 * Private Proof Delegation-CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssueCoSnarkCodeRequest
 */
export interface IssueCoSnarkCodeRequest {
    /**
     * 
     * @type {number}
     * @memberof IssueCoSnarkCodeRequest
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof IssueCoSnarkCodeRequest
     */
    validityInSeconds: number;
}

/**
 * Check if a given object implements the IssueCoSnarkCodeRequest interface.
 */
export function instanceOfIssueCoSnarkCodeRequest(value: object): value is IssueCoSnarkCodeRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('validityInSeconds' in value) || value['validityInSeconds'] === undefined) return false;
    return true;
}

export function IssueCoSnarkCodeRequestFromJSON(json: any): IssueCoSnarkCodeRequest {
    return IssueCoSnarkCodeRequestFromJSONTyped(json, false);
}

export function IssueCoSnarkCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueCoSnarkCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'validityInSeconds': json['validity_in_seconds'],
    };
}

export function IssueCoSnarkCodeRequestToJSON(json: any): IssueCoSnarkCodeRequest {
    return IssueCoSnarkCodeRequestToJSONTyped(json, false);
}

export function IssueCoSnarkCodeRequestToJSONTyped(value?: IssueCoSnarkCodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'validity_in_seconds': value['validityInSeconds'],
    };
}

