/* tslint:disable */
/* eslint-disable */
/**
 * Private Proof Delegation-CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterNpsResponse
 */
export interface RegisterNpsResponse {
    /**
     * 
     * @type {string}
     * @memberof RegisterNpsResponse
     */
    awsAccessKeyId: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterNpsResponse
     */
    awsSecretAccessKeyEnc: string;
    /**
     * 
     * @type {number}
     * @memberof RegisterNpsResponse
     */
    npsId: number;
    /**
     * 
     * @type {string}
     * @memberof RegisterNpsResponse
     */
    s3Bucket: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterNpsResponse
     */
    snsTopic: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterNpsResponse
     */
    sqsQueue: string;
}

/**
 * Check if a given object implements the RegisterNpsResponse interface.
 */
export function instanceOfRegisterNpsResponse(value: object): value is RegisterNpsResponse {
    if (!('awsAccessKeyId' in value) || value['awsAccessKeyId'] === undefined) return false;
    if (!('awsSecretAccessKeyEnc' in value) || value['awsSecretAccessKeyEnc'] === undefined) return false;
    if (!('npsId' in value) || value['npsId'] === undefined) return false;
    if (!('s3Bucket' in value) || value['s3Bucket'] === undefined) return false;
    if (!('snsTopic' in value) || value['snsTopic'] === undefined) return false;
    if (!('sqsQueue' in value) || value['sqsQueue'] === undefined) return false;
    return true;
}

export function RegisterNpsResponseFromJSON(json: any): RegisterNpsResponse {
    return RegisterNpsResponseFromJSONTyped(json, false);
}

export function RegisterNpsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterNpsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'awsAccessKeyId': json['aws_access_key_id'],
        'awsSecretAccessKeyEnc': json['aws_secret_access_key_enc'],
        'npsId': json['nps_id'],
        's3Bucket': json['s3_bucket'],
        'snsTopic': json['sns_topic'],
        'sqsQueue': json['sqs_queue'],
    };
}

export function RegisterNpsResponseToJSON(json: any): RegisterNpsResponse {
    return RegisterNpsResponseToJSONTyped(json, false);
}

export function RegisterNpsResponseToJSONTyped(value?: RegisterNpsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aws_access_key_id': value['awsAccessKeyId'],
        'aws_secret_access_key_enc': value['awsSecretAccessKeyEnc'],
        'nps_id': value['npsId'],
        's3_bucket': value['s3Bucket'],
        'sns_topic': value['snsTopic'],
        'sqs_queue': value['sqsQueue'],
    };
}

