/* tslint:disable */
/* eslint-disable */
/**
 * Private Proof Delegation-CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobType } from './JobType';
import {
    JobTypeFromJSON,
    JobTypeFromJSONTyped,
    JobTypeToJSON,
    JobTypeToJSONTyped,
} from './JobType';

/**
 * 
 * @export
 * @interface ScheduleJobRequest
 */
export interface ScheduleJobRequest {
    /**
     * 
     * @type {number}
     * @memberof ScheduleJobRequest
     */
    blueprintId: number;
    /**
     * 
     * @type {string}
     * @memberof ScheduleJobRequest
     */
    code: string;
    /**
     * 
     * @type {JobType}
     * @memberof ScheduleJobRequest
     */
    jobType: JobType;
}



/**
 * Check if a given object implements the ScheduleJobRequest interface.
 */
export function instanceOfScheduleJobRequest(value: object): value is ScheduleJobRequest {
    if (!('blueprintId' in value) || value['blueprintId'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('jobType' in value) || value['jobType'] === undefined) return false;
    return true;
}

export function ScheduleJobRequestFromJSON(json: any): ScheduleJobRequest {
    return ScheduleJobRequestFromJSONTyped(json, false);
}

export function ScheduleJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'blueprintId': json['blueprint_id'],
        'code': json['code'],
        'jobType': JobTypeFromJSON(json['job_type']),
    };
}

export function ScheduleJobRequestToJSON(json: any): ScheduleJobRequest {
    return ScheduleJobRequestToJSONTyped(json, false);
}

export function ScheduleJobRequestToJSONTyped(value?: ScheduleJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blueprint_id': value['blueprintId'],
        'code': value['code'],
        'job_type': JobTypeToJSON(value['jobType']),
    };
}

