/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BlueprintAccess = {
    Restricted: 'Restricted',
    Public: 'Public'
} as const;
export type BlueprintAccess = typeof BlueprintAccess[keyof typeof BlueprintAccess];


export function instanceOfBlueprintAccess(value: any): boolean {
    for (const key in BlueprintAccess) {
        if (Object.prototype.hasOwnProperty.call(BlueprintAccess, key)) {
            if (BlueprintAccess[key as keyof typeof BlueprintAccess] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BlueprintAccessFromJSON(json: any): BlueprintAccess {
    return BlueprintAccessFromJSONTyped(json, false);
}

export function BlueprintAccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlueprintAccess {
    return json as BlueprintAccess;
}

export function BlueprintAccessToJSON(value?: BlueprintAccess | null): any {
    return value as any;
}

export function BlueprintAccessToJSONTyped(value: any, ignoreDiscriminator: boolean): BlueprintAccess {
    return value as BlueprintAccess;
}

