/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BlueprintType = {
    CircomGroth16: 'CircomGroth16',
    LibsnarkGroth16: 'LibsnarkGroth16',
    NoirUltrahonk: 'NoirUltrahonk'
} as const;
export type BlueprintType = typeof BlueprintType[keyof typeof BlueprintType];


export function instanceOfBlueprintType(value: any): boolean {
    for (const key in BlueprintType) {
        if (Object.prototype.hasOwnProperty.call(BlueprintType, key)) {
            if (BlueprintType[key as keyof typeof BlueprintType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BlueprintTypeFromJSON(json: any): BlueprintType {
    return BlueprintTypeFromJSONTyped(json, false);
}

export function BlueprintTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlueprintType {
    return json as BlueprintType;
}

export function BlueprintTypeToJSON(value?: BlueprintType | null): any {
    return value as any;
}

export function BlueprintTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): BlueprintType {
    return value as BlueprintType;
}

