/* tslint:disable */
/* eslint-disable */
/**
 * Private Proof Delegation-CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BlueprintCurve = {
    Bn254: 'Bn254',
    Bls381: 'Bls381',
    Bls377: 'Bls377'
} as const;
export type BlueprintCurve = typeof BlueprintCurve[keyof typeof BlueprintCurve];


export function instanceOfBlueprintCurve(value: any): boolean {
    for (const key in BlueprintCurve) {
        if (Object.prototype.hasOwnProperty.call(BlueprintCurve, key)) {
            if (BlueprintCurve[key as keyof typeof BlueprintCurve] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BlueprintCurveFromJSON(json: any): BlueprintCurve {
    return BlueprintCurveFromJSONTyped(json, false);
}

export function BlueprintCurveFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlueprintCurve {
    return json as BlueprintCurve;
}

export function BlueprintCurveToJSON(value?: BlueprintCurve | null): any {
    return value as any;
}

export function BlueprintCurveToJSONTyped(value: any, ignoreDiscriminator: boolean): BlueprintCurve {
    return value as BlueprintCurve;
}

