/* tslint:disable */
/* eslint-disable */
/**
 * Private Proof Delegation-CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBlueprintResponse
 */
export interface CreateBlueprintResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateBlueprintResponse
     */
    id: string;
}

/**
 * Check if a given object implements the CreateBlueprintResponse interface.
 */
export function instanceOfCreateBlueprintResponse(value: object): value is CreateBlueprintResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CreateBlueprintResponseFromJSON(json: any): CreateBlueprintResponse {
    return CreateBlueprintResponseFromJSONTyped(json, false);
}

export function CreateBlueprintResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBlueprintResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CreateBlueprintResponseToJSON(json: any): CreateBlueprintResponse {
    return CreateBlueprintResponseToJSONTyped(json, false);
}

export function CreateBlueprintResponseToJSONTyped(value?: CreateBlueprintResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

