/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteCode
 */
export interface InviteCode {
    /**
     * 
     * @type {string}
     * @memberof InviteCode
     */
    distributionMethod?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InviteCode
     */
    inviteCode: string;
    /**
     * 
     * @type {string}
     * @memberof InviteCode
     */
    timestamp: string;
}

/**
 * Check if a given object implements the InviteCode interface.
 */
export function instanceOfInviteCode(value: object): value is InviteCode {
    if (!('inviteCode' in value) || value['inviteCode'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function InviteCodeFromJSON(json: any): InviteCode {
    return InviteCodeFromJSONTyped(json, false);
}

export function InviteCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteCode {
    if (json == null) {
        return json;
    }
    return {
        
        'distributionMethod': json['distribution_method'] == null ? undefined : json['distribution_method'],
        'inviteCode': json['invite_code'],
        'timestamp': json['timestamp'],
    };
}

export function InviteCodeToJSON(json: any): InviteCode {
    return InviteCodeToJSONTyped(json, false);
}

export function InviteCodeToJSONTyped(value?: InviteCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'distribution_method': value['distributionMethod'],
        'invite_code': value['inviteCode'],
        'timestamp': value['timestamp'],
    };
}

