/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobResult } from './JobResult';
import {
    JobResultFromJSON,
    JobResultFromJSONTyped,
    JobResultToJSON,
    JobResultToJSONTyped,
} from './JobResult';

/**
 * 
 * @export
 * @interface JobResults
 */
export interface JobResults {
    /**
     * 
     * @type {JobResult}
     * @memberof JobResults
     */
    result0: JobResult;
    /**
     * 
     * @type {JobResult}
     * @memberof JobResults
     */
    result1: JobResult;
    /**
     * 
     * @type {JobResult}
     * @memberof JobResults
     */
    result2: JobResult;
}

/**
 * Check if a given object implements the JobResults interface.
 */
export function instanceOfJobResults(value: object): value is JobResults {
    if (!('result0' in value) || value['result0'] === undefined) return false;
    if (!('result1' in value) || value['result1'] === undefined) return false;
    if (!('result2' in value) || value['result2'] === undefined) return false;
    return true;
}

export function JobResultsFromJSON(json: any): JobResults {
    return JobResultsFromJSONTyped(json, false);
}

export function JobResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobResults {
    if (json == null) {
        return json;
    }
    return {
        
        'result0': JobResultFromJSON(json['result0']),
        'result1': JobResultFromJSON(json['result1']),
        'result2': JobResultFromJSON(json['result2']),
    };
}

export function JobResultsToJSON(json: any): JobResults {
    return JobResultsToJSONTyped(json, false);
}

export function JobResultsToJSONTyped(value?: JobResults | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result0': JobResultToJSON(value['result0']),
        'result1': JobResultToJSON(value['result1']),
        'result2': JobResultToJSON(value['result2']),
    };
}

