/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MpcProtocol = {
    Rep3: 'Rep3',
    Shamir: 'Shamir'
} as const;
export type MpcProtocol = typeof MpcProtocol[keyof typeof MpcProtocol];


export function instanceOfMpcProtocol(value: any): boolean {
    for (const key in MpcProtocol) {
        if (Object.prototype.hasOwnProperty.call(MpcProtocol, key)) {
            if (MpcProtocol[key as keyof typeof MpcProtocol] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MpcProtocolFromJSON(json: any): MpcProtocol {
    return MpcProtocolFromJSONTyped(json, false);
}

export function MpcProtocolFromJSONTyped(json: any, ignoreDiscriminator: boolean): MpcProtocol {
    return json as MpcProtocol;
}

export function MpcProtocolToJSON(value?: MpcProtocol | null): any {
    return value as any;
}

export function MpcProtocolToJSONTyped(value: any, ignoreDiscriminator: boolean): MpcProtocol {
    return value as MpcProtocol;
}

