/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeProvider
 */
export interface NodeProvider {
    /**
     * 
     * @type {string}
     * @memberof NodeProvider
     */
    encKey: string;
    /**
     * 
     * @type {number}
     * @memberof NodeProvider
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof NodeProvider
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof NodeProvider
     */
    online: boolean;
    /**
     * 
     * @type {string}
     * @memberof NodeProvider
     */
    verifyKey: string;
}

/**
 * Check if a given object implements the NodeProvider interface.
 */
export function instanceOfNodeProvider(value: object): value is NodeProvider {
    if (!('encKey' in value) || value['encKey'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('online' in value) || value['online'] === undefined) return false;
    if (!('verifyKey' in value) || value['verifyKey'] === undefined) return false;
    return true;
}

export function NodeProviderFromJSON(json: any): NodeProvider {
    return NodeProviderFromJSONTyped(json, false);
}

export function NodeProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeProvider {
    if (json == null) {
        return json;
    }
    return {
        
        'encKey': json['enc_key'],
        'id': json['id'],
        'name': json['name'],
        'online': json['online'],
        'verifyKey': json['verify_key'],
    };
}

export function NodeProviderToJSON(json: any): NodeProvider {
    return NodeProviderToJSONTyped(json, false);
}

export function NodeProviderToJSONTyped(value?: NodeProvider | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enc_key': value['encKey'],
        'id': value['id'],
        'name': value['name'],
        'online': value['online'],
        'verify_key': value['verifyKey'],
    };
}

