/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodeProvider } from './NodeProvider';
import {
    NodeProviderFromJSON,
    NodeProviderFromJSONTyped,
    NodeProviderToJSON,
    NodeProviderToJSONTyped,
} from './NodeProvider';

/**
 * 
 * @export
 * @interface NodeProviders
 */
export interface NodeProviders {
    /**
     * 
     * @type {NodeProvider}
     * @memberof NodeProviders
     */
    node0: NodeProvider;
    /**
     * 
     * @type {NodeProvider}
     * @memberof NodeProviders
     */
    node1: NodeProvider;
    /**
     * 
     * @type {NodeProvider}
     * @memberof NodeProviders
     */
    node2: NodeProvider;
}

/**
 * Check if a given object implements the NodeProviders interface.
 */
export function instanceOfNodeProviders(value: object): value is NodeProviders {
    if (!('node0' in value) || value['node0'] === undefined) return false;
    if (!('node1' in value) || value['node1'] === undefined) return false;
    if (!('node2' in value) || value['node2'] === undefined) return false;
    return true;
}

export function NodeProvidersFromJSON(json: any): NodeProviders {
    return NodeProvidersFromJSONTyped(json, false);
}

export function NodeProvidersFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeProviders {
    if (json == null) {
        return json;
    }
    return {
        
        'node0': NodeProviderFromJSON(json['node0']),
        'node1': NodeProviderFromJSON(json['node1']),
        'node2': NodeProviderFromJSON(json['node2']),
    };
}

export function NodeProvidersToJSON(json: any): NodeProviders {
    return NodeProvidersToJSONTyped(json, false);
}

export function NodeProvidersToJSONTyped(value?: NodeProviders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'node0': NodeProviderToJSON(value['node0']),
        'node1': NodeProviderToJSON(value['node1']),
        'node2': NodeProviderToJSON(value['node2']),
    };
}

