/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NpsHeader
 */
export interface NpsHeader {
    /**
     * 
     * @type {number}
     * @memberof NpsHeader
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof NpsHeader
     */
    name: string;
}

/**
 * Check if a given object implements the NpsHeader interface.
 */
export function instanceOfNpsHeader(value: object): value is NpsHeader {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function NpsHeaderFromJSON(json: any): NpsHeader {
    return NpsHeaderFromJSONTyped(json, false);
}

export function NpsHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): NpsHeader {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function NpsHeaderToJSON(json: any): NpsHeader {
    return NpsHeaderToJSONTyped(json, false);
}

export function NpsHeaderToJSONTyped(value?: NpsHeader | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

