/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NpsKeyMaterial
 */
export interface NpsKeyMaterial {
    /**
     * 
     * @type {string}
     * @memberof NpsKeyMaterial
     */
    encKey: string;
    /**
     * 
     * @type {string}
     * @memberof NpsKeyMaterial
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NpsKeyMaterial
     */
    verifyKey: string;
}

/**
 * Check if a given object implements the NpsKeyMaterial interface.
 */
export function instanceOfNpsKeyMaterial(value: object): value is NpsKeyMaterial {
    if (!('encKey' in value) || value['encKey'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('verifyKey' in value) || value['verifyKey'] === undefined) return false;
    return true;
}

export function NpsKeyMaterialFromJSON(json: any): NpsKeyMaterial {
    return NpsKeyMaterialFromJSONTyped(json, false);
}

export function NpsKeyMaterialFromJSONTyped(json: any, ignoreDiscriminator: boolean): NpsKeyMaterial {
    if (json == null) {
        return json;
    }
    return {
        
        'encKey': json['enc_key'],
        'name': json['name'],
        'verifyKey': json['verify_key'],
    };
}

export function NpsKeyMaterialToJSON(json: any): NpsKeyMaterial {
    return NpsKeyMaterialToJSONTyped(json, false);
}

export function NpsKeyMaterialToJSONTyped(value?: NpsKeyMaterial | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enc_key': value['encKey'],
        'name': value['name'],
        'verify_key': value['verifyKey'],
    };
}

