/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationResultNpsHeaderElementsInner } from './PaginationResultNpsHeaderElementsInner';
import {
    PaginationResultNpsHeaderElementsInnerFromJSON,
    PaginationResultNpsHeaderElementsInnerFromJSONTyped,
    PaginationResultNpsHeaderElementsInnerToJSON,
    PaginationResultNpsHeaderElementsInnerToJSONTyped,
} from './PaginationResultNpsHeaderElementsInner';

/**
 * 
 * @export
 * @interface PaginationResultNpsHeader
 */
export interface PaginationResultNpsHeader {
    /**
     * 
     * @type {Array<PaginationResultNpsHeaderElementsInner>}
     * @memberof PaginationResultNpsHeader
     */
    elements: Array<PaginationResultNpsHeaderElementsInner>;
    /**
     * 
     * @type {number}
     * @memberof PaginationResultNpsHeader
     */
    totalAmount?: number | null;
}

/**
 * Check if a given object implements the PaginationResultNpsHeader interface.
 */
export function instanceOfPaginationResultNpsHeader(value: object): value is PaginationResultNpsHeader {
    if (!('elements' in value) || value['elements'] === undefined) return false;
    return true;
}

export function PaginationResultNpsHeaderFromJSON(json: any): PaginationResultNpsHeader {
    return PaginationResultNpsHeaderFromJSONTyped(json, false);
}

export function PaginationResultNpsHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResultNpsHeader {
    if (json == null) {
        return json;
    }
    return {
        
        'elements': ((json['elements'] as Array<any>).map(PaginationResultNpsHeaderElementsInnerFromJSON)),
        'totalAmount': json['total_amount'] == null ? undefined : json['total_amount'],
    };
}

export function PaginationResultNpsHeaderToJSON(json: any): PaginationResultNpsHeader {
    return PaginationResultNpsHeaderToJSONTyped(json, false);
}

export function PaginationResultNpsHeaderToJSONTyped(value?: PaginationResultNpsHeader | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'elements': ((value['elements'] as Array<any>).map(PaginationResultNpsHeaderElementsInnerToJSON)),
        'total_amount': value['totalAmount'],
    };
}

