/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationResultNpsElementsInner } from './PaginationResultNpsElementsInner';
import {
    PaginationResultNpsElementsInnerFromJSON,
    PaginationResultNpsElementsInnerFromJSONTyped,
    PaginationResultNpsElementsInnerToJSON,
    PaginationResultNpsElementsInnerToJSONTyped,
} from './PaginationResultNpsElementsInner';

/**
 * 
 * @export
 * @interface PaginationResultNps
 */
export interface PaginationResultNps {
    /**
     * 
     * @type {Array<PaginationResultNpsElementsInner>}
     * @memberof PaginationResultNps
     */
    elements: Array<PaginationResultNpsElementsInner>;
    /**
     * 
     * @type {number}
     * @memberof PaginationResultNps
     */
    totalAmount?: number | null;
}

/**
 * Check if a given object implements the PaginationResultNps interface.
 */
export function instanceOfPaginationResultNps(value: object): value is PaginationResultNps {
    if (!('elements' in value) || value['elements'] === undefined) return false;
    return true;
}

export function PaginationResultNpsFromJSON(json: any): PaginationResultNps {
    return PaginationResultNpsFromJSONTyped(json, false);
}

export function PaginationResultNpsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResultNps {
    if (json == null) {
        return json;
    }
    return {
        
        'elements': ((json['elements'] as Array<any>).map(PaginationResultNpsElementsInnerFromJSON)),
        'totalAmount': json['total_amount'] == null ? undefined : json['total_amount'],
    };
}

export function PaginationResultNpsToJSON(json: any): PaginationResultNps {
    return PaginationResultNpsToJSONTyped(json, false);
}

export function PaginationResultNpsToJSONTyped(value?: PaginationResultNps | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'elements': ((value['elements'] as Array<any>).map(PaginationResultNpsElementsInnerToJSON)),
        'total_amount': value['totalAmount'],
    };
}

