/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationResultNpsElementsInner
 */
export interface PaginationResultNpsElementsInner {
    /**
     * 
     * @type {number}
     * @memberof PaginationResultNpsElementsInner
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PaginationResultNpsElementsInner
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationResultNpsElementsInner
     */
    online: boolean;
}

/**
 * Check if a given object implements the PaginationResultNpsElementsInner interface.
 */
export function instanceOfPaginationResultNpsElementsInner(value: object): value is PaginationResultNpsElementsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('online' in value) || value['online'] === undefined) return false;
    return true;
}

export function PaginationResultNpsElementsInnerFromJSON(json: any): PaginationResultNpsElementsInner {
    return PaginationResultNpsElementsInnerFromJSONTyped(json, false);
}

export function PaginationResultNpsElementsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResultNpsElementsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'online': json['online'],
    };
}

export function PaginationResultNpsElementsInnerToJSON(json: any): PaginationResultNpsElementsInner {
    return PaginationResultNpsElementsInnerToJSONTyped(json, false);
}

export function PaginationResultNpsElementsInnerToJSONTyped(value?: PaginationResultNpsElementsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'online': value['online'],
    };
}

