/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationResultInviteCodeElementsInner } from './PaginationResultInviteCodeElementsInner';
import {
    PaginationResultInviteCodeElementsInnerFromJSON,
    PaginationResultInviteCodeElementsInnerFromJSONTyped,
    PaginationResultInviteCodeElementsInnerToJSON,
    PaginationResultInviteCodeElementsInnerToJSONTyped,
} from './PaginationResultInviteCodeElementsInner';

/**
 * 
 * @export
 * @interface PaginationResultInviteCode
 */
export interface PaginationResultInviteCode {
    /**
     * 
     * @type {Array<PaginationResultInviteCodeElementsInner>}
     * @memberof PaginationResultInviteCode
     */
    elements: Array<PaginationResultInviteCodeElementsInner>;
    /**
     * 
     * @type {number}
     * @memberof PaginationResultInviteCode
     */
    totalAmount?: number | null;
}

/**
 * Check if a given object implements the PaginationResultInviteCode interface.
 */
export function instanceOfPaginationResultInviteCode(value: object): value is PaginationResultInviteCode {
    if (!('elements' in value) || value['elements'] === undefined) return false;
    return true;
}

export function PaginationResultInviteCodeFromJSON(json: any): PaginationResultInviteCode {
    return PaginationResultInviteCodeFromJSONTyped(json, false);
}

export function PaginationResultInviteCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResultInviteCode {
    if (json == null) {
        return json;
    }
    return {
        
        'elements': ((json['elements'] as Array<any>).map(PaginationResultInviteCodeElementsInnerFromJSON)),
        'totalAmount': json['total_amount'] == null ? undefined : json['total_amount'],
    };
}

export function PaginationResultInviteCodeToJSON(json: any): PaginationResultInviteCode {
    return PaginationResultInviteCodeToJSONTyped(json, false);
}

export function PaginationResultInviteCodeToJSONTyped(value?: PaginationResultInviteCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'elements': ((value['elements'] as Array<any>).map(PaginationResultInviteCodeElementsInnerToJSON)),
        'total_amount': value['totalAmount'],
    };
}

