/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationResultString
 */
export interface PaginationResultString {
    /**
     * 
     * @type {Array<string>}
     * @memberof PaginationResultString
     */
    elements: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof PaginationResultString
     */
    totalAmount?: number | null;
}

/**
 * Check if a given object implements the PaginationResultString interface.
 */
export function instanceOfPaginationResultString(value: object): value is PaginationResultString {
    if (!('elements' in value) || value['elements'] === undefined) return false;
    return true;
}

export function PaginationResultStringFromJSON(json: any): PaginationResultString {
    return PaginationResultStringFromJSONTyped(json, false);
}

export function PaginationResultStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResultString {
    if (json == null) {
        return json;
    }
    return {
        
        'elements': json['elements'],
        'totalAmount': json['total_amount'] == null ? undefined : json['total_amount'],
    };
}

export function PaginationResultStringToJSON(json: any): PaginationResultString {
    return PaginationResultStringToJSONTyped(json, false);
}

export function PaginationResultStringToJSONTyped(value?: PaginationResultString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'elements': value['elements'],
        'total_amount': value['totalAmount'],
    };
}

