/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationResultNpsHeaderElementsInner
 */
export interface PaginationResultNpsHeaderElementsInner {
    /**
     * 
     * @type {number}
     * @memberof PaginationResultNpsHeaderElementsInner
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PaginationResultNpsHeaderElementsInner
     */
    name: string;
}

/**
 * Check if a given object implements the PaginationResultNpsHeaderElementsInner interface.
 */
export function instanceOfPaginationResultNpsHeaderElementsInner(value: object): value is PaginationResultNpsHeaderElementsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PaginationResultNpsHeaderElementsInnerFromJSON(json: any): PaginationResultNpsHeaderElementsInner {
    return PaginationResultNpsHeaderElementsInnerFromJSONTyped(json, false);
}

export function PaginationResultNpsHeaderElementsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResultNpsHeaderElementsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function PaginationResultNpsHeaderElementsInnerToJSON(json: any): PaginationResultNpsHeaderElementsInner {
    return PaginationResultNpsHeaderElementsInnerToJSONTyped(json, false);
}

export function PaginationResultNpsHeaderElementsInnerToJSONTyped(value?: PaginationResultNpsHeaderElementsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

