/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationResultInviteCodeElementsInner
 */
export interface PaginationResultInviteCodeElementsInner {
    /**
     * 
     * @type {string}
     * @memberof PaginationResultInviteCodeElementsInner
     */
    distributionMethod?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginationResultInviteCodeElementsInner
     */
    inviteCode: string;
    /**
     * 
     * @type {string}
     * @memberof PaginationResultInviteCodeElementsInner
     */
    timestamp: string;
}

/**
 * Check if a given object implements the PaginationResultInviteCodeElementsInner interface.
 */
export function instanceOfPaginationResultInviteCodeElementsInner(value: object): value is PaginationResultInviteCodeElementsInner {
    if (!('inviteCode' in value) || value['inviteCode'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function PaginationResultInviteCodeElementsInnerFromJSON(json: any): PaginationResultInviteCodeElementsInner {
    return PaginationResultInviteCodeElementsInnerFromJSONTyped(json, false);
}

export function PaginationResultInviteCodeElementsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResultInviteCodeElementsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'distributionMethod': json['distribution_method'] == null ? undefined : json['distribution_method'],
        'inviteCode': json['invite_code'],
        'timestamp': json['timestamp'],
    };
}

export function PaginationResultInviteCodeElementsInnerToJSON(json: any): PaginationResultInviteCodeElementsInner {
    return PaginationResultInviteCodeElementsInnerToJSONTyped(json, false);
}

export function PaginationResultInviteCodeElementsInnerToJSONTyped(value?: PaginationResultInviteCodeElementsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'distribution_method': value['distributionMethod'],
        'invite_code': value['inviteCode'],
        'timestamp': value['timestamp'],
    };
}

