/* tslint:disable */
/* eslint-disable */
/**
 * TACEO:Proof - CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProofResult
 */
export interface ProofResult {
    /**
     * 
     * @type {string}
     * @memberof ProofResult
     */
    proof: string;
    /**
     * 
     * @type {string}
     * @memberof ProofResult
     */
    publicInputs: string;
}

/**
 * Check if a given object implements the ProofResult interface.
 */
export function instanceOfProofResult(value: object): value is ProofResult {
    if (!('proof' in value) || value['proof'] === undefined) return false;
    if (!('publicInputs' in value) || value['publicInputs'] === undefined) return false;
    return true;
}

export function ProofResultFromJSON(json: any): ProofResult {
    return ProofResultFromJSONTyped(json, false);
}

export function ProofResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofResult {
    if (json == null) {
        return json;
    }
    return {
        
        'proof': json['proof'],
        'publicInputs': json['public_inputs'],
    };
}

export function ProofResultToJSON(json: any): ProofResult {
    return ProofResultToJSONTyped(json, false);
}

export function ProofResultToJSONTyped(value?: ProofResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'proof': value['proof'],
        'public_inputs': value['publicInputs'],
    };
}

