/* tslint:disable */
/* eslint-disable */
/**
 * Private Proof Delegation-CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterNpsRequest
 */
export interface RegisterNpsRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterNpsRequest
     */
    cert: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterNpsRequest
     */
    encKey: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterNpsRequest
     */
    grpcUrl: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterNpsRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterNpsRequest
     */
    verifyingKey: string;
}

/**
 * Check if a given object implements the RegisterNpsRequest interface.
 */
export function instanceOfRegisterNpsRequest(value: object): value is RegisterNpsRequest {
    if (!('cert' in value) || value['cert'] === undefined) return false;
    if (!('encKey' in value) || value['encKey'] === undefined) return false;
    if (!('grpcUrl' in value) || value['grpcUrl'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('verifyingKey' in value) || value['verifyingKey'] === undefined) return false;
    return true;
}

export function RegisterNpsRequestFromJSON(json: any): RegisterNpsRequest {
    return RegisterNpsRequestFromJSONTyped(json, false);
}

export function RegisterNpsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterNpsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cert': json['cert'],
        'encKey': json['enc_key'],
        'grpcUrl': json['grpc_url'],
        'name': json['name'],
        'verifyingKey': json['verifying_key'],
    };
}

export function RegisterNpsRequestToJSON(json: any): RegisterNpsRequest {
    return RegisterNpsRequestToJSONTyped(json, false);
}

export function RegisterNpsRequestToJSONTyped(value?: RegisterNpsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cert': value['cert'],
        'enc_key': value['encKey'],
        'grpc_url': value['grpcUrl'],
        'name': value['name'],
        'verifying_key': value['verifyingKey'],
    };
}

