/* tslint:disable */
/* eslint-disable */
/**
 * Private Proof Delegation-CCL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@taceo.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NpsKeyMaterial } from './NpsKeyMaterial';
import {
    NpsKeyMaterialFromJSON,
    NpsKeyMaterialFromJSONTyped,
    NpsKeyMaterialToJSON,
    NpsKeyMaterialToJSONTyped,
} from './NpsKeyMaterial';

/**
 * 
 * @export
 * @interface ScheduleJobResponse
 */
export interface ScheduleJobResponse {
    /**
     * 
     * @type {string}
     * @memberof ScheduleJobResponse
     */
    jobId: string;
    /**
     * 
     * @type {Array<NpsKeyMaterial>}
     * @memberof ScheduleJobResponse
     */
    keyMaterial: Array<NpsKeyMaterial>;
    /**
     * 
     * @type {number}
     * @memberof ScheduleJobResponse
     */
    remainingPermits: number;
}

/**
 * Check if a given object implements the ScheduleJobResponse interface.
 */
export function instanceOfScheduleJobResponse(value: object): value is ScheduleJobResponse {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('keyMaterial' in value) || value['keyMaterial'] === undefined) return false;
    if (!('remainingPermits' in value) || value['remainingPermits'] === undefined) return false;
    return true;
}

export function ScheduleJobResponseFromJSON(json: any): ScheduleJobResponse {
    return ScheduleJobResponseFromJSONTyped(json, false);
}

export function ScheduleJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['job_id'],
        'keyMaterial': ((json['key_material'] as Array<any>).map(NpsKeyMaterialFromJSON)),
        'remainingPermits': json['remaining_permits'],
    };
}

export function ScheduleJobResponseToJSON(json: any): ScheduleJobResponse {
    return ScheduleJobResponseToJSONTyped(json, false);
}

export function ScheduleJobResponseToJSONTyped(value?: ScheduleJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['jobId'],
        'key_material': ((value['keyMaterial'] as Array<any>).map(NpsKeyMaterialToJSON)),
        'remaining_permits': value['remainingPermits'],
    };
}

